Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,20 +11,22 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+      - uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.9
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
 
-    - name: Check variable k
-      run: |
-        if [ "$(python -c 'from main import k; print(k)')" == "6" ]; then
-          echo "Test passed"
-          exit 0
-        else
-          echo "Test failed"
-          exit 1
+      - name: Check variable k
+        run: |
+          value=$(python -c 'from main import k; print(k)')
+          if [ "$value" == "6" ]; then
+            echo "Test passed"
+            exit 0
+          else
+            echo "Test failed"
+            exit 1
+
 
 
